//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:56:48 PM CET 
//


package org.programirame.report.model.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for detailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="virtualhost" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="portinfo" type="{}portinfoType"/&gt;
 *         &lt;element name="cvss_score" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="cvss_vector" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cvss_vector_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="risk" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="family" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="information" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="falsepositive" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="solutiontitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="solution" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="referencelist" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cve" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bug" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="verify" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="history" type="{}historyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detailType", propOrder = {
    "ip",
    "hostname",
    "platform",
    "date",
    "virtualhost",
    "id",
    "name",
    "portinfo",
    "cvssScore",
    "cvssVector",
    "cvssVectorDescription",
    "risk",
    "family",
    "product",
    "description",
    "information",
    "falsepositive",
    "solutiontitle",
    "solution",
    "category",
    "referencelist",
    "cve",
    "bug",
    "verify",
    "history"
})
public class DetailType {

    @XmlElement(required = true)
    protected String ip;
    @XmlElement(required = true)
    protected String hostname;
    @XmlElement(required = true)
    protected String platform;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String virtualhost;
    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected PortinfoType portinfo;
    @XmlElement(name = "cvss_score", required = true)
    protected BigDecimal cvssScore;
    @XmlElement(name = "cvss_vector", required = true)
    protected String cvssVector;
    @XmlElement(name = "cvss_vector_description", required = true)
    protected String cvssVectorDescription;
    protected int risk;
    @XmlElement(required = true)
    protected String family;
    @XmlElement(required = true)
    protected String product;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String information;
    protected int falsepositive;
    @XmlElement(required = true)
    protected String solutiontitle;
    @XmlElement(required = true)
    protected String solution;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String referencelist;
    @XmlElement(required = true)
    protected CveType cve;
    @XmlElement(required = true)
    protected String bug;
    @XmlElement(required = true)
    protected String verify;
    @XmlElement(required = true)
    protected HistoryType history;

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the virtualhost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualhost() {
        return virtualhost;
    }

    /**
     * Sets the value of the virtualhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualhost(String value) {
        this.virtualhost = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the portinfo property.
     * 
     * @return
     *     possible object is
     *     {@link PortinfoType }
     *     
     */
    public PortinfoType getPortinfo() {
        return portinfo;
    }

    /**
     * Sets the value of the portinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortinfoType }
     *     
     */
    public void setPortinfo(PortinfoType value) {
        this.portinfo = value;
    }

    /**
     * Gets the value of the cvssScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCvssScore() {
        return cvssScore;
    }

    /**
     * Sets the value of the cvssScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCvssScore(BigDecimal value) {
        this.cvssScore = value;
    }

    /**
     * Gets the value of the cvssVector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvssVector() {
        return cvssVector;
    }

    /**
     * Sets the value of the cvssVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvssVector(String value) {
        this.cvssVector = value;
    }

    /**
     * Gets the value of the cvssVectorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvssVectorDescription() {
        return cvssVectorDescription;
    }

    /**
     * Sets the value of the cvssVectorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvssVectorDescription(String value) {
        this.cvssVectorDescription = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     */
    public int getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     */
    public void setRisk(int value) {
        this.risk = value;
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the information property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformation() {
        return information;
    }

    /**
     * Sets the value of the information property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformation(String value) {
        this.information = value;
    }

    /**
     * Gets the value of the falsepositive property.
     * 
     */
    public int getFalsepositive() {
        return falsepositive;
    }

    /**
     * Sets the value of the falsepositive property.
     * 
     */
    public void setFalsepositive(int value) {
        this.falsepositive = value;
    }

    /**
     * Gets the value of the solutiontitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolutiontitle() {
        return solutiontitle;
    }

    /**
     * Sets the value of the solutiontitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolutiontitle(String value) {
        this.solutiontitle = value;
    }

    /**
     * Gets the value of the solution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolution() {
        return solution;
    }

    /**
     * Sets the value of the solution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolution(String value) {
        this.solution = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the referencelist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencelist() {
        return referencelist;
    }

    /**
     * Sets the value of the referencelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencelist(String value) {
        this.referencelist = value;
    }

    /**
     * Gets the value of the cve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public CveType getCve() {
        return cve;
    }

    /**
     * Sets the value of the cve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCve(CveType value) {
        this.cve = value;
    }

    /**
     * Gets the value of the bug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBug() {
        return bug;
    }

    /**
     * Sets the value of the bug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBug(String value) {
        this.bug = value;
    }

    /**
     * Gets the value of the verify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerify() {
        return verify;
    }

    /**
     * Sets the value of the verify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerify(String value) {
        this.verify = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryType }
     *     
     */
    public HistoryType getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryType }
     *     
     */
    public void setHistory(HistoryType value) {
        this.history = value;
    }

}
