//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:56:48 PM CET 
//


package org.programirame.report.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mainType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reportinfo" type="{}reportinfoType"/&gt;
 *         &lt;element name="detaillist" type="{}detaillistType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mainType", propOrder = {
    "report",
    "reportinfo",
    "detaillist"
})
@XmlRootElement(name="main")
public class MainType {

    @XmlElement(required = true)
    protected String report;
    @XmlElement(required = true)
    protected ReportinfoType reportinfo;
    @XmlElement(required = true)
    protected DetaillistType detaillist;

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReport(String value) {
        this.report = value;
    }

    /**
     * Gets the value of the reportinfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReportinfoType }
     *     
     */
    public ReportinfoType getReportinfo() {
        return reportinfo;
    }

    /**
     * Sets the value of the reportinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportinfoType }
     *     
     */
    public void setReportinfo(ReportinfoType value) {
        this.reportinfo = value;
    }

    /**
     * Gets the value of the detaillist property.
     * 
     * @return
     *     possible object is
     *     {@link DetaillistType }
     *     
     */
    public DetaillistType getDetaillist() {
        return detaillist;
    }

    /**
     * Sets the value of the detaillist property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetaillistType }
     *     
     */
    public void setDetaillist(DetaillistType value) {
        this.detaillist = value;
    }

}
