//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:56:48 PM CET 
//


package org.programirame.report.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reportinfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reportinfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="selectedschedulejob" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="test" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="threat" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportinfoType", propOrder = {
    "type",
    "id",
    "creator",
    "selectedschedulejob",
    "date",
    "test",
    "threat"
})
public class ReportinfoType {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String creator;
    @XmlElement(required = true)
    protected String selectedschedulejob;
    @XmlElement(required = true)
    protected String date;
    protected int test;
    protected int threat;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the selectedschedulejob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedschedulejob() {
        return selectedschedulejob;
    }

    /**
     * Sets the value of the selectedschedulejob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedschedulejob(String value) {
        this.selectedschedulejob = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the test property.
     * 
     */
    public int getTest() {
        return test;
    }

    /**
     * Sets the value of the test property.
     * 
     */
    public void setTest(int value) {
        this.test = value;
    }

    /**
     * Gets the value of the threat property.
     * 
     */
    public int getThreat() {
        return threat;
    }

    /**
     * Sets the value of the threat property.
     * 
     */
    public void setThreat(int value) {
        this.threat = value;
    }

}
